<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soccf-tr5-001" name="component-tests(failed)" tests="3" failures="2" timestamp="15 Sep 2014 10:44:36 GMT" time="57.089" errors="0">
  <testcase name="testAll" time="1.092" classname="teammates.test.cases.logic.EvaluationsLogicTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;1&amp;gt; but was:&amp;lt;0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at teammates.test.cases.logic.EvaluationsLogicTest.testGetEvaluationsClosingWithinTimeLimit(EvaluationsLogicTest.java:273)
	at teammates.test.cases.logic.EvaluationsLogicTest.testAll(EvaluationsLogicTest.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAll -->
  <testcase name="testAll" time="4.041" classname="teammates.test.cases.logic.FeedbackSessionsLogicTest"/>
  <testcase name="testAdditionOfTaskToTaskQueue" time="41.598" classname="teammates.test.automated.FeedbackSessionPublishedReminderTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;3&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<3> but was:<2>
	at teammates.test.automated.FeedbackSessionPublishedReminderTest.testAdditionOfTaskToTaskQueue(FeedbackSessionPublishedReminderTest.java:137)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAdditionOfTaskToTaskQueue -->
</testsuite> <!-- component-tests(failed) -->
